import { type CreationOptional, DataTypes, type InferAttributes, type InferCreationAttributes, Model } from 'sequelize';

import { type Hours } from '../utils/schemas.ts';

import { sequelize } from '../utils/db.js';

class Gym extends Model<InferAttributes<Gym>, InferCreationAttributes<Gym>> {
  declare id: CreationOptional<string>;
  declare name: string;
  declare chain: string | null | undefined;
  declare street: string;
  declare streetNumber: string;
  declare city: string;
  declare openingHours: CreationOptional<Hours>;
  declare url: string | null | undefined;
  declare notes: string | null | undefined;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;
};

Gym.init({
  id: {
    type: DataTypes.UUID,  // CHAR(36) for MySQL
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false
  },
  chain: {
    type: DataTypes.STRING
  },
  street: {
    type: DataTypes.STRING,
    allowNull: false
  },
  streetNumber: {
    type: DataTypes.STRING,
    allowNull: false
  },
  city: {
    type: DataTypes.STRING,
    allowNull: false
  },
  openingHours: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: {}
  },
  url: {
    type: DataTypes.STRING
  },
  notes: {
    type: DataTypes.STRING
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  sequelize,
  underscored: true,
  modelName: 'gym'
});

export default Gym;