import {
  type BelongsToManyGetAssociationsMixin,
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model
} from 'sequelize';

import { adjustUserRole } from '../utils/middleware.ts';

import { type Hours } from '../utils/schemas.ts';

import { sequelize } from '../utils/db.js';

import User from './user.ts';

class Gym extends Model<InferAttributes<Gym>, InferCreationAttributes<Gym>> {
  declare id: CreationOptional<string>;
  declare name: string;
  declare chain: string | null | undefined;
  declare street: string;
  declare streetNumber: string;
  declare city: string;
  declare openingHours: CreationOptional<Hours>;
  declare url: string | null | undefined;
  declare notes: string | null | undefined;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  declare getUsers: BelongsToManyGetAssociationsMixin<User>;
};

Gym.init({
  id: {
    type: DataTypes.UUID,  // CHAR(36) for MySQL
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false
  },
  chain: {
    type: DataTypes.STRING
  },
  street: {
    type: DataTypes.STRING,
    allowNull: false
  },
  streetNumber: {
    type: DataTypes.STRING,
    allowNull: false
  },
  city: {
    type: DataTypes.STRING,
    allowNull: false
  },
  openingHours: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: {}
  },
  url: {
    type: DataTypes.STRING
  },
  notes: {
    type: DataTypes.STRING
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  hooks: {
    beforeDestroy: async (gym) => {  // Turn gym-less managers into gym-goers.
      const managers = await gym.getUsers();
      for (const manager of managers) {
        await adjustUserRole(manager.id, 1);  // emptyLength = 1 because this is run before .destroy() and its CASCADE
      }
    }
  },
  sequelize,
  underscored: true,
  modelName: 'gym'
});

export default Gym;