/* eslint-disable @stylistic/lines-between-class-members */
import {
  type BelongsToManyAddAssociationMixin,
  type BelongsToManyGetAssociationsMixin,
  type BelongsToManyRemoveAssociationMixin,
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model
} from 'sequelize';

import { adjustUserRole } from '../utils/middleware.ts';

import type {
  Hours,
  HoursExceptions
} from '@strength-inventory/schemas';

import { sequelize } from '../utils/db.js';

import { Equipment, Membership, User } from './index.ts';

class Gym extends Model<InferAttributes<Gym>, InferCreationAttributes<Gym>> {
  declare id: CreationOptional<string>;
  declare name: string;
  declare chain: string;
  declare street: string;
  declare streetNumber: string;
  declare district: string;
  declare city: string;
  declare country: string;
  declare openingHoursEveryone: CreationOptional<Hours>;
  declare openingHoursMembers: CreationOptional<Hours>;
  declare openingHoursExceptions: CreationOptional<HoursExceptions>;
  declare url: string | null | undefined;
  declare location: string;
  declare equipmentVisible: boolean;
  declare membershipsVisible: boolean;
  declare openingHoursVisible: boolean;
  declare notes: string;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  declare getManagers: BelongsToManyGetAssociationsMixin<User>;
  declare getMemberships: BelongsToManyGetAssociationsMixin<Membership>;
  declare addMembership: BelongsToManyAddAssociationMixin<Membership, string>;
  declare removeMembership:
  BelongsToManyRemoveAssociationMixin<Membership, string>;
  declare getEquipment: BelongsToManyGetAssociationsMixin<Equipment>;
  declare addEquipment: BelongsToManyAddAssociationMixin<Equipment, string>;
  declare removeEquipment:
  BelongsToManyRemoveAssociationMixin<Equipment, string>;
}

Gym.init({
  id: {
    type: DataTypes.UUID,  // CHAR(36) for MySQL
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false
  },
  chain: {
    type: DataTypes.STRING
  },
  street: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, 60]
    }
  },
  streetNumber: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, 20]
    }
  },
  district: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, 60]
    }
  },
  city: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, 60]
    }
  },
  country: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, 40]
    }
  },
  openingHoursEveryone: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: {}
  },
  openingHoursMembers: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: {}
  },
  openingHoursExceptions: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: {}
  },
  url: {
    type: DataTypes.STRING,
    validate: {
      isUrl: true
    }
  },
  location: {
    type: DataTypes.STRING(510),
    allowNull: false,
    validate: {
      isUrl: true
    }
  },
  equipmentVisible: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false
  },
  membershipsVisible: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false
  },
  openingHoursVisible: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false
  },
  notes: {
    type: DataTypes.STRING
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  hooks: {
    beforeDestroy: async (gym) => {  // Turn gym-less managers into gym-goers.
      const managers = await gym.getManagers();
      for (const manager of managers) {
        await adjustUserRole(
          manager.id,
          1  // emptyLength = 1 because this is run before .destroy()
        );
      }
    }
  },
  sequelize,
  underscored: true,
  modelName: 'gym'
});

export default Gym;
