/* eslint-disable @stylistic/lines-between-class-members */
import {
  type BelongsToManyGetAssociationsMixin,
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model
} from 'sequelize';

import type {
  MembershipAvailability,
  MembershipTimeUnit
} from '@strength-inventory/schemas';

import { sequelize } from '../utils/db.js';

import { Gym } from './index.ts';

class Membership extends Model<
  InferAttributes<Membership>, InferCreationAttributes<Membership>
> {
  declare id: CreationOptional<string>;
  declare chain: string | null | undefined;
  declare name: string;
  declare feeCurrency: string;
  declare membershipFee: number;
  declare validity: number;
  declare validityUnit: MembershipTimeUnit;
  declare commitment: number | null | undefined;
  declare commitmentUnit: MembershipTimeUnit | null | undefined;
  declare initiationFee: number | null | undefined;
  declare availability: MembershipAvailability;
  declare url: string | null | undefined;
  declare notes: string | null | undefined;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  declare getGyms: BelongsToManyGetAssociationsMixin<Gym>;
}

Membership.init({
  id: {
    type: DataTypes.UUID,  // CHAR(36) for MySQL
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
  },
  chain: {
    type: DataTypes.STRING
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false
  },
  feeCurrency: {
    type: DataTypes.STRING,
    allowNull: false
  },
  membershipFee: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: false
  },
  validity: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  validityUnit: {
    type: DataTypes.ENUM('year', 'month', 'week', 'day', 'hour'),
    allowNull: false
  },
  commitment: {
    type: DataTypes.INTEGER
  },
  commitmentUnit: {
    type: DataTypes.ENUM('year', 'month', 'week', 'day', 'hour')
    // As per customValidator(), this field is required if commitment !== null.
  },
  initiationFee: {
    type: DataTypes.DECIMAL(10, 2)
  },
  availability: {
    type: DataTypes.JSON,
    allowNull: false
  },
  url: {
    type: DataTypes.STRING
  },
  notes: {
    type: DataTypes.STRING
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  sequelize,
  underscored: true,
  modelName: 'membership',
  validate: {
    customValidator () {
      const instance = this as Membership;

      if (!instance.commitmentUnit && instance.commitment) {
        throw new Error(
          'commitment unit must be selected if there is commitment'
        );
      }
    }
  }
});

export default Membership;
