PUT http://localhost:3000/api/memberships/025a7acc-c51d-4447-911d-8d9cd6641658
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4MDJlMmE5LWE3YWUtNDZmMS04OTFjLTdkNWIwNDhjYTRmNiIsInVzZXJuYW1lIjoiVGhlQWRtaW4iLCJpYXQiOjE3NzM4MjgzNjh9.WzbXTA9Oe0pBL3jmaGbv2d05UFKfEte-npGE6wtaydo
// admins only

{
  "chain": "Liikku",
  "name": "Järki-Liikku",
  "feeCurrency": "euro",
  "membershipFee": 34.90,
  "validity": 1,
  "validityUnit": "month",
  "commitment": 12,
  "CommitmentUnit": "month",
  "initiationFee": 29.90,
  "availability": {
    "Desk": true,
    "Web": true,
    "App": false,
    "Other": false
  },
  "notes": "Turns into Jousto-Liikku after commitment."
}