POST http://localhost:3000/api/equipment
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4MDJlMmE5LWE3YWUtNDZmMS04OTFjLTdkNWIwNDhjYTRmNiIsInVzZXJuYW1lIjoiVGhlQWRtaW4iLCJpYXQiOjE3NzM5MTY1NzB9.r2STEdXL6N7sWTDX_EY9s1evLTdXlh5A3dfOQvCv2vY
// admins only

{
  "name": "Matrix Ultra Rotary Torso",
  "category": "strengthMachine",
  "manufacturer": "Matrix",
  "code": "G7-S55",
  "weightUnit": "kg",
  "startingWeight": 4.5,
  "availableWeights": [9.0, 13.5, 18.0, 22.5, 27.0, 31.5, 36.0, 40.5, 45.0, 49.5, 54.0, 58.5, 63.0, 67.5, 72.0, 76.5, 81.0, 85.5, 90.0],
  "maximumWeight": 93.4,
  "url": "https://world.matrixfitness.com/eng/strength/single-station/g7-s55-rotary-torso",
  "notes": "Also available in Ultra Base option G7-S55B."
}