POST http://localhost:3000/api/memberships/
Content-Type: application/json

{
  "chain": "Liikku",
  "name": "Järki-Liikku",
  "feeCurrency": "euro",
  "membershipFee": 34.90,
  "validity": 1,
  "validityUnit": "month",
  "commitment": 12,
  "CommitmentUnit": "month",
  "initiationFee": 29.90,
  "availability": {
    "Desk": true,
    "Web": true,
    "App": false,
    "Other": false
  },
  "notes": "Turns into Jousto-Liikku after commitment."
}