PATCH http://localhost:3000/api/users/015cf6bf-a86c-452e-8270-99225ef9af22/password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxNWNmNmJmLWE4NmMtNDUyZS04MjcwLTk5MjI1ZWY5YWYyMiIsInVzZXJuYW1lIjoiVGhlQWRtaW4iLCJpYXQiOjE3Njk3NjgwOTd9.IS9VlR4N5oet-1GSpkdo8KZlyD_BKKlRUY3-MKfSNE8
// users themselves only

{
  "password": "StrongTodayStrongerTomorrow"
}