POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "LashaTalakhadze",
  "email": "lasha@talakhadze.ge",
  "password": "ILiftThereforeIAm",
  "name": "Lasha Talakhadze",
}