POST http://localhost:3000/api/gyms
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4MDJlMmE5LWE3YWUtNDZmMS04OTFjLTdkNWIwNDhjYTRmNiIsInVzZXJuYW1lIjoiVGhlQWRtaW4iLCJpYXQiOjE3NzEzMzYzODl9.r_BBfO31OEvNibI6aULjMFmC-wKKC43sz_H66CVCKc8
// admins only

{
      "name": "Mayor's Gym",
      "street": "Porkkalankatu",
      "streetNumber": "13N",
      "city": "Helsinki",
      "notes": "Changes in pricing effective February 1, 2026",
      "openingHours": {
        "MO": [
          0,
          24
        ],
        "TU": [
          0,
          24
        ],
        "WE": [
          0,
          24
        ],
        "TH": [
          0,
          24
        ],
        "FR": [
          0,
          24
        ],
        "SA": [
          0,
          24
        ],
        "SU": [
          0,
          24
        ]
      }
    }