/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAuthRouteImport } from './routes/_noAuth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as NoAuthIndexRouteImport } from './routes/_noAuth/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as NoAuthopenGymsRouteImport } from './routes/_noAuth/(open)/gyms'
import { Route as NoAuthopenEquipmentRouteImport } from './routes/_noAuth/(open)/equipment'
import { Route as AuthenticatedAdminMembershipsRouteImport } from './routes/_authenticated/admin.memberships'
import { Route as AuthenticatedAdminGymsRouteImport } from './routes/_authenticated/admin.gyms'
import { Route as AuthenticatedAdminEquipmentRouteImport } from './routes/_authenticated/admin.equipment'

const NoAuthRoute = NoAuthRouteImport.update({
  id: '/_noAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAuthIndexRoute = NoAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoAuthRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAuthopenGymsRoute = NoAuthopenGymsRouteImport.update({
  id: '/(open)/gyms',
  path: '/gyms',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthopenEquipmentRoute = NoAuthopenEquipmentRouteImport.update({
  id: '/(open)/equipment',
  path: '/equipment',
  getParentRoute: () => NoAuthRoute,
} as any)
const AuthenticatedAdminMembershipsRoute =
  AuthenticatedAdminMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGymsRoute = AuthenticatedAdminGymsRouteImport.update({
  id: '/gyms',
  path: '/gyms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEquipmentRoute =
  AuthenticatedAdminEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof NoAuthIndexRoute
  '/login': typeof authLoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/gyms': typeof AuthenticatedAdminGymsRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/equipment': typeof NoAuthopenEquipmentRoute
  '/gyms': typeof NoAuthopenGymsRoute
}
export interface FileRoutesByTo {
  '/': typeof NoAuthIndexRoute
  '/login': typeof authLoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/gyms': typeof AuthenticatedAdminGymsRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/equipment': typeof NoAuthopenEquipmentRoute
  '/gyms': typeof NoAuthopenGymsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_noAuth': typeof NoAuthRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_noAuth/': typeof NoAuthIndexRoute
  '/_authenticated/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/_authenticated/admin/gyms': typeof AuthenticatedAdminGymsRoute
  '/_authenticated/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/_noAuth/(open)/equipment': typeof NoAuthopenEquipmentRoute
  '/_noAuth/(open)/gyms': typeof NoAuthopenGymsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/equipment'
    | '/admin/gyms'
    | '/admin/memberships'
    | '/equipment'
    | '/gyms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/equipment'
    | '/admin/gyms'
    | '/admin/memberships'
    | '/equipment'
    | '/gyms'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_noAuth'
    | '/(auth)/login'
    | '/_authenticated/admin'
    | '/_noAuth/'
    | '/_authenticated/admin/equipment'
    | '/_authenticated/admin/gyms'
    | '/_authenticated/admin/memberships'
    | '/_noAuth/(open)/equipment'
    | '/_noAuth/(open)/gyms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  NoAuthRoute: typeof NoAuthRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_noAuth': {
      id: '/_noAuth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NoAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_noAuth/': {
      id: '/_noAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NoAuthIndexRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_noAuth/(open)/gyms': {
      id: '/_noAuth/(open)/gyms'
      path: '/gyms'
      fullPath: '/gyms'
      preLoaderRoute: typeof NoAuthopenGymsRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_noAuth/(open)/equipment': {
      id: '/_noAuth/(open)/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof NoAuthopenEquipmentRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_authenticated/admin/memberships': {
      id: '/_authenticated/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AuthenticatedAdminMembershipsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gyms': {
      id: '/_authenticated/admin/gyms'
      path: '/gyms'
      fullPath: '/admin/gyms'
      preLoaderRoute: typeof AuthenticatedAdminGymsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipment': {
      id: '/_authenticated/admin/equipment'
      path: '/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AuthenticatedAdminEquipmentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEquipmentRoute: typeof AuthenticatedAdminEquipmentRoute
  AuthenticatedAdminGymsRoute: typeof AuthenticatedAdminGymsRoute
  AuthenticatedAdminMembershipsRoute: typeof AuthenticatedAdminMembershipsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEquipmentRoute: AuthenticatedAdminEquipmentRoute,
  AuthenticatedAdminGymsRoute: AuthenticatedAdminGymsRoute,
  AuthenticatedAdminMembershipsRoute: AuthenticatedAdminMembershipsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NoAuthRouteChildren {
  NoAuthIndexRoute: typeof NoAuthIndexRoute
  NoAuthopenEquipmentRoute: typeof NoAuthopenEquipmentRoute
  NoAuthopenGymsRoute: typeof NoAuthopenGymsRoute
}

const NoAuthRouteChildren: NoAuthRouteChildren = {
  NoAuthIndexRoute: NoAuthIndexRoute,
  NoAuthopenEquipmentRoute: NoAuthopenEquipmentRoute,
  NoAuthopenGymsRoute: NoAuthopenGymsRoute,
}

const NoAuthRouteWithChildren =
  NoAuthRoute._addFileChildren(NoAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  NoAuthRoute: NoAuthRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
