/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as personalAdminRouteImport } from './routes/(personal)/admin'
import { Route as openGymsRouteImport } from './routes/(open)/gyms'
import { Route as openEquipmentRouteImport } from './routes/(open)/equipment'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const personalAdminRoute = personalAdminRouteImport.update({
  id: '/(personal)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const openGymsRoute = openGymsRouteImport.update({
  id: '/(open)/gyms',
  path: '/gyms',
  getParentRoute: () => rootRouteImport,
} as any)
const openEquipmentRoute = openEquipmentRouteImport.update({
  id: '/(open)/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/equipment': typeof openEquipmentRoute
  '/gyms': typeof openGymsRoute
  '/admin': typeof personalAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/equipment': typeof openEquipmentRoute
  '/gyms': typeof openGymsRoute
  '/admin': typeof personalAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(open)/equipment': typeof openEquipmentRoute
  '/(open)/gyms': typeof openGymsRoute
  '/(personal)/admin': typeof personalAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/equipment' | '/gyms' | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/equipment' | '/gyms' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(open)/equipment'
    | '/(open)/gyms'
    | '/(personal)/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  openEquipmentRoute: typeof openEquipmentRoute
  openGymsRoute: typeof openGymsRoute
  personalAdminRoute: typeof personalAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(personal)/admin': {
      id: '/(personal)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof personalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(open)/gyms': {
      id: '/(open)/gyms'
      path: '/gyms'
      fullPath: '/gyms'
      preLoaderRoute: typeof openGymsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(open)/equipment': {
      id: '/(open)/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof openEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  openEquipmentRoute: openEquipmentRoute,
  openGymsRoute: openGymsRoute,
  personalAdminRoute: personalAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
